name: Build project and run Lighthouse CI
on: [push]

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Write credentials.ts
        run: 'echo "${{ secrets.DEV_CREDENTIALS }}" > src/app/credentials.ts'

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      # Switch to Node.js 16.x for running Lighthouse CI
      - name: Use Node.js 16.x for Lighthouse CI
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Run Lighthouse CI using Node.js 16
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
